import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

// Translations
const translations = {
  ru: {
    // General
    dashboard: 'Дашборд',
    professional_analytics: 'Профессиональная крипто-аналитика',
    refresh: 'Обновить',
    loading: 'Загрузка...',
    no_data: 'Нет данных',
    view_more: 'Подробнее',
    source: 'Источник',
    updated: 'Обновлено',
    
    // Tabs
    tab_market: 'Обзор рынка',
    tab_derivatives: 'Деривативы',
    tab_etf: 'ETF Аналитика',
    tab_onchain: 'Ончейн',
    tab_altseason: 'Альтсезон',
    tab_predictions: 'Предсказания',
    tab_risk: 'Риск-движок',
    tab_ai: 'AI Сигналы',
    tab_portfolio: 'Портфель',
    tab_war: 'Режим войны',
    
    // Sidebar
    portfolio: 'Портфель',
    portfolio_my: 'Мой портфель',
    portfolio_rukos: 'Портфель RUKOS_CRYPTO',
    admin_panel: 'Админ-панель',
    
    // Market Core
    market_core_title: 'Обзор рынка',
    market_core_desc: 'Макроэкономические показатели и общее состояние крипторынка. Отслеживайте капитализацию, доминирование BTC/ETH, корреляцию с традиционными рынками.',
    total_market_cap: 'Общая капитализация',
    btc_dominance: 'Доминирование BTC',
    eth_dominance: 'Доминирование ETH',
    total3: 'TOTAL3 (Альты)',
    total3_desc: 'Капитализация всех криптовалют кроме BTC и ETH',
    stablecoins: 'Стейблкоины',
    stablecoins_desc: 'Общая капитализация USDT + USDC',
    traditional_markets: 'Традиционные рынки',
    traditional_markets_desc: 'Корреляция крипты с традиционными активами',
    global_liquidity: 'Глобальная ликвидность',
    global_liquidity_desc: 'M2 денежная масса влияет на риск-аппетит инвесторов',
    market_regime: 'Режим рынка',
    market_regime_desc: 'Риск-Он: инвесторы готовы к риску. Риск-Офф: уход в безопасные активы',
    risk_on: 'Риск-Он',
    risk_off: 'Риск-Офф',
    crypto_prices: 'Цены криптовалют',
    crypto_prices_desc: 'Актуальные цены топ-криптовалют с CoinGecko',
    fear_greed: 'Индекс страха и жадности',
    fear_greed_desc: '0-25: Крайний страх, 25-45: Страх, 45-55: Нейтрально, 55-75: Жадность, 75-100: Крайняя жадность',
    gold: 'Золото',
    
    // Derivatives
    derivatives_title: 'Панель деривативов',
    derivatives_desc: 'Анализ деривативов: Открытый интерес, Ставка фандинга, Соотношение лонг/шорт. Ключевые метрики для понимания позиционирования трейдеров.',
    open_interest: 'Открытый интерес',
    open_interest_desc: 'Общий объём открытых позиций. Рост OI + рост цены = подтверждение тренда',
    funding_rate: 'Ставка фандинга',
    funding_rate_desc: 'Положительный: лонги платят шортам. Высокий фандинг = перегрев рынка',
    long_short_ratio: 'Соотн. лонг/шорт',
    long_short_ratio_desc: 'Соотношение длинных к коротким позициям',
    liquidation_clusters: 'Кластеры ликвидаций',
    liquidation_clusters_desc: 'Ценовые уровни с высокой концентрацией ликвидаций',
    funding_history: 'История ставки фандинга',
    top_traders: 'Топ трейдеры',
    top_traders_desc: 'Позиционирование крупных трейдеров на Hyperliquid',
    gamma_exposure: 'Гамма экспозиция',
    gamma_exposure_desc: 'Гамма экспозиция маркет-мейкеров влияет на волатильность',
    oi_divergence: 'OI Дивергенция',
    oi_divergence_desc: 'Расхождение между OI и ценой - сигнал разворота',
    
    // ETF Intelligence
    etf_title: 'Аналитика ETF потоков',
    etf_desc: 'Потоки в крипто-ETF: BlackRock, Fidelity, Grayscale и др. Институциональный спрос - ключевой драйвер цены.',
    total_aum: 'Всего AUM',
    daily_flow: 'Дневной поток',
    cumulative_flow: 'Кумулятивно',
    etf_absorption: 'ETF Абсорбция',
    etf_absorption_desc: 'Сигнал когда ETF покупают больше, чем майнеры продают',
    miner_activity: 'Активность майнеров',
    flow_history: 'История потоков',
    fund_breakdown: 'По фондам',
    pct_spot_volume: '% от спот объёма',
    premium_discount: 'Премия/Дисконт',
    flow_correlation: 'Корреляция Flow-Price',
    all_etfs: 'Все ETF',
    btc_etfs: 'BTC ETF',
    eth_etfs: 'ETH ETF',
    
    // Onchain
    onchain_title: 'Ончейн данные',
    onchain_desc: 'Ончейн метрики: SOPR, NUPL, MVRV, потоки на биржи. Данные напрямую из блокчейна.',
    sopr: 'SOPR',
    sopr_desc: 'Коэффициент потраченных выходов. >1: продажа в прибыль, <1: в убыток',
    nupl: 'NUPL',
    nupl_desc: 'Чистая нереализованная прибыль/убыток. Показывает % нереализованной прибыли в сети',
    mvrv: 'MVRV',
    mvrv_desc: 'Рыночная стоимость к реализованной. >3: перекуплен, <1: перепродан',
    cdd: 'CDD',
    cdd_desc: 'Уничтожение монетодней. Высокий = старые монеты двигаются',
    exchange_flows: 'Потоки на биржи',
    exchange_flows_desc: 'Приток на биржи = давление продаж. Отток = накопление',
    whale_zones: 'Зоны накопления китов',
    notable_wallets: 'Известные кошельки',
    notable_wallets_desc: 'Балансы крупнейших публичных держателей',
    miner_reserves: 'Резервы майнеров',
    realized_vs_market: 'Реализ. vs Рыночная кап.',
    
    // Altseason
    altseason_title: 'Монитор альтсезона',
    altseason_desc: 'Мониторинг альтсезона: доминирование BTC, перформанс альтов, секторальная ротация.',
    altseason_probability: 'Вероятность альтсезона',
    altseason_probability_desc: 'Комплексный индекс на основе BTC.D, перформанса альтов, TVL',
    dominance_breakdown: 'Распределение доминирования',
    sector_performance: 'Перформанс секторов',
    top50_vs_btc: 'Топ-50 vs BTC',
    narrative_heatmap: 'Карта нарративов',
    defi_tvl: 'DeFi TVL',
    altseason: 'АЛЬТСЕЗОН',
    warming_up: 'РАЗОГРЕВ',
    btc_season: 'BTC СЕЗОН',
    
    // Risk Engine
    risk_title: 'Движок рисков',
    risk_desc: 'Система оценки рисков: волатильность, левередж, стейблкоин потоки, сигналы перегрева.',
    risk_score: 'Индекс риска',
    risk_score_desc: 'Комплексная оценка риска от 1 до 10',
    volatility_index: 'Индекс волатильности',
    volatility_desc: 'DVOL - подразумеваемая волатильность из опционов',
    market_regime_risk: 'Режим рынка',
    market_regime_risk_desc: 'ТРЕНД: направленное движение. БОКОВИК: консолидация. РАСПРЕДЕЛЕНИЕ: потенциальная вершина',
    leverage_crowding: 'Скопление плеча',
    leverage_crowding_desc: 'Уровень концентрации плеча в системе',
    stablecoin_flows: 'Потоки стейблкоинов',
    stablecoin_flows_desc: 'Минтинг стейблов = приток капитала в крипту',
    overheat_alerts: 'Сигналы перегрева',
    overheat_alerts_desc: 'Предупреждения о перегреве рынка',
    
    // AI Signals
    ai_title: 'AI Панель сигналов',
    ai_desc: 'Мультифакторный AI-анализ: ончейн + деривативы + ETF + макро + сентимент.',
    composite_signal: 'Композитный сигнал',
    composite_signal_desc: 'Агрегированный сигнал из 5 факторов',
    squeeze_probability: 'Вероятность сквиза',
    squeeze_desc: 'Сквиз шортов: принудительное закрытие шортов. Сквиз лонгов: ликвидация лонгов',
    liquidity_zones: 'Зоны ликвидности',
    liquidity_zones_desc: 'Уровни с высокой концентрацией ликвидности',
    weekly_range: 'Недельный диапазон',
    weekly_range_desc: 'Прогнозируемый диапазон цены на неделю',
    key_levels: 'Ключевые уровни',
    exchange_reserves: 'Резервы на биржах',
    risk_factors: 'Факторы риска',
    signal_factors: 'Факторы сигнала',
    short_squeeze: 'Сквиз шортов',
    long_squeeze: 'Сквиз лонгов',
    extreme_fear: 'Крайний страх',
    extreme_greed: 'Крайняя жадность',
    basis: 'Базис',
    net_flow: 'Нетто-поток',
    
    // Portfolio
    portfolio_title: 'Трекер портфеля',
    portfolio_desc: 'Отслеживание портфеля: позиции, прибыль/убыток, риск-метрики, расстояние до ликвидации.',
    total_value: 'Стоимость портфеля',
    unrealized_pnl: 'Нереализ. прибыль/убыток',
    positions: 'Позиции',
    risk_metrics: 'Риск метрики',
    avg_leverage: 'Средний левередж',
    risk_per_trade: 'Риск на сделку',
    risk_of_ruin: 'Риск разорения',
    risk_of_ruin_desc: 'Вероятность потери депозита при текущем риске',
    liq_distance: 'До ликвидации',
    concentration: 'Концентрация',
    
    // War Mode
    war_title: 'Режим войны',
    war_desc: 'Режим стресса рынка: мониторинг аномалий фандинга, OI, ETF, китов, ликвидаций.',
    stress_level: 'Уровень стресса',
    stress_level_desc: 'Агрегированный показатель стресса рынка',
    active_alerts: 'Активные алерты',
    quick_actions: 'Быстрые действия',
    reduce_all: 'Сократить всё',
    add_hedges: 'Добавить хедж',
    set_stops: 'Поставить стопы',
    to_stables: 'В стейблы',
    
    // Common
    bullish: 'Бычий',
    bearish: 'Медвежий',
    neutral: 'Нейтральный',
    high: 'Высокий',
    medium: 'Средний',
    low: 'Низкий',
    extreme: 'Экстремальный',
    normal: 'Нормальный',
    inflow: 'Приток',
    outflow: 'Отток',
    
    // Navigation
    posts: 'Посты',
    ideas: 'Идеи',
    chat: 'Чат',
    settings: 'Настройки',
    ai_assistant: 'AI Ассистент',
    collapse: 'Свернуть',
    logout: 'Выйти',
    
    // Additional translations
    previous_day: 'Предыдущий день',
    previous_week: 'Предыдущая неделя',
    total_stablecoin_mcap: 'Капитализация стейблов',
    global_m2_supply: 'Глобальная денежная масса M2',
    mom: 'м/м',
    long_accounts: 'Лонг аккаунты',
    short_accounts: 'Шорт аккаунты',
    whale_sentiment: 'Сентимент китов',
    total_gamma: 'Общая гамма',
    max_pain: 'Макс. боль',
    gamma_flip: 'Переворот гаммы',
    dealer_position: 'Позиция дилера',
    etf_absorption_bullish: 'ETF покупают больше, чем майнеры продают',
    etf_absorption_bearish: 'Майнеры продают больше, чем ETF покупают',
    funds: 'фондов',
    days_14: '14 дней',
    daily_miner_sell: 'Дневная продажа майнеров',
    usd_value: 'Стоимость USD',
    price: 'Цена',
    total_staked: 'Всего застейкано',
    staking_ratio: 'Доля стейкинга',
    validators: 'Валидаторы',
    avg_apy: 'Средняя APY',
    market_cap_label: 'Рыночная кап.',
    realized_cap: 'Реализованная кап.',
    total_reserves: 'Общие резервы',
    change_30d: 'Изменение 30д',
    action: 'Действие',
    btc_dvol: 'BTC DVOL',
    eth_dvol: 'ETH DVOL',
    usdt_minted: 'USDT создано',
    usdc_minted: 'USDC создано',
    signal: 'Сигнал',
    btc_on_exchanges: 'BTC на биржах',
    strength: 'Сила',
    range: 'Диапазон',
    strong_support: 'Сильная поддержка',
    immediate_support: 'Ближняя поддержка',
    immediate_resistance: 'Ближнее сопротивление',
    strong_resistance: 'Сильное сопротивление',
    account_balance: 'Баланс аккаунта',
    units_at: 'шт по',
    value: 'Стоимость',
    exposure: 'Экспозиция',
    liquidation_price: 'Цена ликвидации',
    leverage_exposure: 'Экспозиция плеча',
    min: 'мин.',
    war_mode_active: 'РЕЖИМ ВОЙНЫ АКТИВЕН',
    all_clear: 'Всё в порядке',
    no_stress_signals: 'Нет активных сигналов стресса',
    alerts: 'АЛЕРТОВ',
    yes: 'Да',
    no: 'Нет',
    volume: 'Объём',
    liquidity: 'Ликвидность',
    activity: 'Активность',
    markets: 'рынков',
    total_volume: 'Общий объём',
    total_liquidity: 'Общая ликвидность',
    source_label: 'Источник',
    extreme_change: 'Экстремальное изменение',
    market_activity_24h: 'Активность рынка 24ч',
    daily_turnover: 'Дневной оборот',
    avg_probability: 'Средняя вероятность',
    avg_yes_across_markets: 'Среднее "Да" по рынкам',
    high_confidence: 'Высокая уверенность',
    no_high_confidence: 'Нет событий с высокой уверенностью',
    hold: 'ДЕРЖАТЬ',
    alts: 'АЛЬТЫ',
    hi_risk: 'ВЫСОКИЙ РИСК',
    pnl: 'Прибыль/Убыток',
    positions_count: 'поз.',
    pieces: 'шт',
    entry: 'Вход',
    current: 'Сейчас',
    my_portfolio_label: 'Мой портфель',
    portfolio_empty: 'Портфель пуст. Добавьте первую позицию!',
    add_position: 'Добавить позицию',
    portfolio_management: 'Управление позициями и отслеживание PnL',
    low_risk_portfolio: 'Low-risk портфель от команды. Только для просмотра.',
    portfolio_not_configured: 'Портфель RUKOS_CRYPTO пока не настроен администратором.',
    edit_position: 'Редактировать позицию',
    fill_all_fields: 'Заполните все поля',
    position_updated: 'Позиция обновлена',
    position_added: 'Позиция добавлена',
    position_deleted: 'Позиция удалена',
    delete_error: 'Ошибка удаления',
    error: 'Ошибка',
    save: 'Сохранить',
    add: 'Добавить',
    ticker_placeholder: 'Тикер (BTC, ETH, SOL...)',
    amount: 'Количество',
    entry_price: 'Цена входа ($)',
    note_optional: 'Заметка (опционально)',
    total2_desc: 'Всё кроме BTC',
    total3_label: 'Всё кроме BTC/ETH',
    outperforming: 'опережают',
    total_value_locked: 'Общая заблокированная стоимость',
    total: 'Всего',
    
    // Risk levels & statuses
    status_medium: 'СРЕДНИЙ',
    status_high: 'ВЫСОКИЙ',
    status_low: 'НИЗКИЙ',
    status_extreme: 'ЭКСТРЕМАЛЬНЫЙ',
    status_critical: 'КРИТИЧЕСКИЙ',
    status_elevated: 'ПОВЫШЕННЫЙ',
    status_dangerous: 'ОПАСНЫЙ',
    status_normal: 'НОРМАЛЬНЫЙ',
    
    // Alert types
    alert_funding_spike: 'СКАЧОК ФАНДИНГА',
    alert_oi_divergence: 'OI ДИВЕРГЕНЦИЯ',
    alert_whale_move: 'ДВИЖЕНИЕ КИТОВ',
    alert_liquidation: 'ЛИКВИДАЦИЯ',
    oi_spike: 'СКАЧОК OI',
    whale_move: 'ДВИЖЕНИЕ КИТОВ',
    funding_spike: 'СКАЧОК ФАНДИНГА',
    liquidation: 'ЛИКВИДАЦИЯ',
    
    // API messages translations
    msg_funding_overheated: 'Ставка фандинга - рынок перегрет',
    msg_oi_price_flat: 'OI вырос, цена неподвижна',
    msg_price_down_oi_up: 'Цена вниз, OI вверх',
  },
  
  en: {
    // General
    dashboard: 'Dashboard',
    professional_analytics: 'Professional crypto analytics',
    refresh: 'Refresh',
    loading: 'Loading...',
    no_data: 'No data',
    view_more: 'View more',
    source: 'Source',
    updated: 'Updated',
    
    // Tabs
    tab_market: 'Market Core',
    tab_derivatives: 'Derivatives',
    tab_etf: 'ETF Intelligence',
    tab_onchain: 'Onchain',
    tab_altseason: 'Altseason',
    tab_predictions: 'Predictions',
    tab_risk: 'Risk Engine',
    tab_ai: 'AI Signals',
    tab_portfolio: 'Portfolio',
    tab_war: 'War Mode',
    
    // Sidebar
    portfolio: 'Portfolio',
    portfolio_my: 'My Portfolio',
    portfolio_rukos: 'RUKOS_CRYPTO Portfolio',
    admin_panel: 'Admin Panel',
    
    // Market Core
    market_core_title: 'Market Core',
    market_core_desc: 'Macroeconomic indicators and overall crypto market state. Track market cap, BTC/ETH dominance, correlation with traditional markets.',
    total_market_cap: 'Total Market Cap',
    btc_dominance: 'BTC Dominance',
    eth_dominance: 'ETH Dominance',
    total3: 'TOTAL3 (Alts)',
    total3_desc: 'Market cap of all cryptocurrencies except BTC and ETH',
    stablecoins: 'Stablecoins',
    stablecoins_desc: 'Total market cap of USDT + USDC',
    traditional_markets: 'Traditional Markets',
    traditional_markets_desc: 'Crypto correlation with traditional assets',
    global_liquidity: 'Global Liquidity',
    global_liquidity_desc: 'M2 money supply affects investor risk appetite',
    market_regime: 'Market Regime',
    market_regime_desc: 'Risk-on: investors seeking risk. Risk-off: flight to safety',
    risk_on: 'Risk-On',
    risk_off: 'Risk-Off',
    crypto_prices: 'Crypto Prices',
    crypto_prices_desc: 'Live prices of top cryptocurrencies from CoinGecko',
    fear_greed: 'Fear & Greed Index',
    fear_greed_desc: '0-25: Extreme Fear, 25-45: Fear, 45-55: Neutral, 55-75: Greed, 75-100: Extreme Greed',
    gold: 'Gold',
    
    // Derivatives
    derivatives_title: 'Derivatives Control Panel',
    derivatives_desc: 'Derivatives analysis: Open Interest, Funding Rate, Long/Short Ratio. Key metrics for understanding trader positioning.',
    open_interest: 'Open Interest',
    open_interest_desc: 'Total open positions. Rising OI + rising price = trend confirmation',
    funding_rate: 'Funding Rate',
    funding_rate_desc: 'Positive: longs pay shorts. High funding = market overheated',
    long_short_ratio: 'Long/Short Ratio',
    long_short_ratio_desc: 'Ratio of long to short positions',
    liquidation_clusters: 'Liquidation Clusters',
    liquidation_clusters_desc: 'Price levels with high liquidation concentration',
    funding_history: 'Funding Rate History',
    top_traders: 'Top Traders',
    top_traders_desc: 'Large trader positioning on Hyperliquid',
    gamma_exposure: 'Gamma Exposure',
    gamma_exposure_desc: 'Market maker gamma exposure affects volatility',
    oi_divergence: 'OI Divergence',
    oi_divergence_desc: 'Divergence between OI and price - reversal signal',
    
    // ETF Intelligence
    etf_title: 'ETF Flow Intelligence',
    etf_desc: 'Crypto ETF flows: BlackRock, Fidelity, Grayscale etc. Institutional demand is a key price driver.',
    total_aum: 'Total AUM',
    daily_flow: 'Daily Flow',
    cumulative_flow: 'Cumulative',
    etf_absorption: 'ETF Absorption',
    etf_absorption_desc: 'Signal when ETFs buy more than miners sell',
    miner_activity: 'Miner Activity',
    flow_history: 'Flow History',
    fund_breakdown: 'By Fund',
    pct_spot_volume: '% of Spot Volume',
    premium_discount: 'Premium/Discount',
    flow_correlation: 'Flow-Price Correlation',
    all_etfs: 'All ETFs',
    btc_etfs: 'BTC ETFs',
    eth_etfs: 'ETH ETFs',
    
    // Onchain
    onchain_title: 'Onchain War Room',
    onchain_desc: 'Onchain metrics: SOPR, NUPL, MVRV, exchange flows. Data directly from the blockchain.',
    sopr: 'SOPR',
    sopr_desc: 'Spent Output Profit Ratio. >1: selling at profit, <1: at loss',
    nupl: 'NUPL',
    nupl_desc: 'Net Unrealized Profit/Loss. Shows % of unrealized profit in network',
    mvrv: 'MVRV',
    mvrv_desc: 'Market Value to Realized Value. >3: overbought, <1: oversold',
    cdd: 'CDD',
    cdd_desc: 'Coin Days Destroyed. High = old coins moving',
    exchange_flows: 'Exchange Flows',
    exchange_flows_desc: 'Inflow to exchanges = sell pressure. Outflow = accumulation',
    whale_zones: 'Whale Accumulation Zones',
    notable_wallets: 'Notable Wallets',
    notable_wallets_desc: 'Balances of largest public holders',
    miner_reserves: 'Miner Reserves',
    realized_vs_market: 'Realized vs Market Cap',
    
    // Altseason
    altseason_title: 'Altseason Monitor',
    altseason_desc: 'Altseason monitoring: BTC dominance, alt performance, sector rotation.',
    altseason_probability: 'Altseason Probability',
    altseason_probability_desc: 'Composite index based on BTC.D, alt performance, TVL',
    dominance_breakdown: 'Dominance Breakdown',
    sector_performance: 'Sector Performance',
    top50_vs_btc: 'Top 50 vs BTC',
    narrative_heatmap: 'Narrative Heatmap',
    defi_tvl: 'DeFi TVL',
    altseason: 'ALTSEASON',
    warming_up: 'WARMING UP',
    btc_season: 'BTC SEASON',
    
    // Risk Engine
    risk_title: 'Risk Engine',
    risk_desc: 'Risk assessment system: volatility, leverage, stablecoin flows, overheat signals.',
    risk_score: 'Risk Score',
    risk_score_desc: 'Composite risk assessment from 1 to 10',
    volatility_index: 'Volatility Index',
    volatility_desc: 'DVOL - implied volatility from options',
    market_regime_risk: 'Market Regime',
    market_regime_risk_desc: 'TREND: directional move. CHOP: sideways. DISTRIBUTION: distribution',
    leverage_crowding: 'Leverage Crowding',
    leverage_crowding_desc: 'Level of leverage concentration in the system',
    stablecoin_flows: 'Stablecoin Flows',
    stablecoin_flows_desc: 'Stablecoin minting = capital inflow to crypto',
    overheat_alerts: 'Overheat Alerts',
    overheat_alerts_desc: 'Market overheat warnings',
    
    // AI Signals
    ai_title: 'AI Signal Panel',
    ai_desc: 'Multi-factor AI analysis: onchain + derivatives + ETF + macro + sentiment.',
    composite_signal: 'Composite Signal',
    composite_signal_desc: 'Aggregated signal from 5 factors',
    squeeze_probability: 'Squeeze Probability',
    squeeze_desc: 'Short squeeze: forced short closing. Long squeeze: long liquidation',
    liquidity_zones: 'Liquidity Zones',
    liquidity_zones_desc: 'Levels with high liquidity concentration',
    weekly_range: 'Weekly Range',
    weekly_range_desc: 'Predicted price range for the week',
    key_levels: 'Key Levels',
    exchange_reserves: 'Exchange Reserves',
    risk_factors: 'Risk Factors',
    signal_factors: 'Signal Factors',
    short_squeeze: 'Short Squeeze',
    long_squeeze: 'Long Squeeze',
    extreme_fear: 'Extreme Fear',
    extreme_greed: 'Extreme Greed',
    basis: 'Basis',
    net_flow: 'Net Flow',
    
    // Portfolio
    portfolio_title: 'Portfolio Tracker',
    portfolio_desc: 'Portfolio tracking: positions, PnL, risk metrics, liquidation distance.',
    total_value: 'Portfolio Value',
    unrealized_pnl: 'Unrealized PnL',
    positions: 'Positions',
    risk_metrics: 'Risk Metrics',
    avg_leverage: 'Avg Leverage',
    risk_per_trade: 'Risk per Trade',
    risk_of_ruin: 'Risk of Ruin',
    risk_of_ruin_desc: 'Probability of losing deposit at current risk',
    liq_distance: 'To Liquidation',
    concentration: 'Concentration',
    
    // War Mode
    war_title: 'War Mode',
    war_desc: 'Market stress mode: monitoring funding, OI, ETF, whale moves, liquidation anomalies.',
    stress_level: 'Stress Level',
    stress_level_desc: 'Aggregated market stress indicator',
    active_alerts: 'Active Alerts',
    quick_actions: 'Quick Actions',
    reduce_all: 'Reduce All',
    add_hedges: 'Add Hedges',
    set_stops: 'Set Stops',
    to_stables: 'To Stables',
    
    // Common
    bullish: 'Bullish',
    bearish: 'Bearish',
    neutral: 'Neutral',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    extreme: 'Extreme',
    normal: 'Normal',
    inflow: 'Inflow',
    outflow: 'Outflow',
    
    // Navigation
    posts: 'Posts',
    ideas: 'Ideas',
    chat: 'Chat',
    settings: 'Settings',
    ai_assistant: 'AI Assistant',
    collapse: 'Collapse',
    logout: 'Logout',
    
    // Additional translations
    previous_day: 'Previous Day',
    previous_week: 'Previous Week',
    total_stablecoin_mcap: 'Total Stablecoin MCap',
    global_m2_supply: 'Global M2 Money Supply',
    mom: 'MoM',
    long_accounts: 'Long Accounts',
    short_accounts: 'Short Accounts',
    whale_sentiment: 'Whale Sentiment',
    total_gamma: 'Total Gamma',
    max_pain: 'Max Pain',
    gamma_flip: 'Gamma Flip',
    dealer_position: 'Dealer Position',
    etf_absorption_bullish: 'ETFs buying more than miners sell',
    etf_absorption_bearish: 'Miners selling exceeds ETF buying',
    funds: 'funds',
    days_14: '14 Days',
    daily_miner_sell: 'Daily Miner Sell',
    usd_value: 'USD Value',
    price: 'Price',
    total_staked: 'Total Staked',
    staking_ratio: 'Staking Ratio',
    validators: 'Validators',
    avg_apy: 'Avg APY',
    market_cap_label: 'Market Cap',
    realized_cap: 'Realized Cap',
    total_reserves: 'Total Reserves',
    change_30d: '30d Change',
    action: 'Action',
    btc_dvol: 'BTC DVOL',
    eth_dvol: 'ETH DVOL',
    usdt_minted: 'USDT Minted',
    usdc_minted: 'USDC Minted',
    signal: 'Signal',
    btc_on_exchanges: 'BTC on Exchanges',
    strength: 'Strength',
    range: 'Range',
    strong_support: 'Strong Support',
    immediate_support: 'Immediate Support',
    immediate_resistance: 'Immediate Resistance',
    strong_resistance: 'Strong Resistance',
    account_balance: 'Account Balance',
    units_at: 'units @',
    value: 'Value',
    exposure: 'Exposure',
    liquidation_price: 'Liquidation Price',
    leverage_exposure: 'Leverage Exposure',
    min: 'Min',
    war_mode_active: 'WAR MODE ACTIVE',
    all_clear: 'All Clear',
    no_stress_signals: 'No active stress signals detected',
    alerts: 'ALERTS',
    yes: 'Yes',
    no: 'No',
    volume: 'Volume',
    liquidity: 'Liquidity',
    activity: 'Activity',
    markets: 'markets',
    total_volume: 'Total Volume',
    total_liquidity: 'Total Liquidity',
    source_label: 'Source',
    extreme_change: 'Extreme Change',
    market_activity_24h: 'Market Activity 24h',
    daily_turnover: 'Daily Turnover',
    avg_probability: 'Avg Probability',
    avg_yes_across_markets: 'Avg "Yes" across markets',
    high_confidence: 'High Confidence',
    no_high_confidence: 'No high confidence events',
    hold: 'HOLD',
    alts: 'ALTs',
    hi_risk: 'HI RISK',
    pnl: 'PnL',
    positions_count: 'pos.',
    pieces: 'pcs',
    entry: 'Entry',
    current: 'Current',
    my_portfolio_label: 'My Portfolio',
    portfolio_empty: 'Portfolio is empty. Add your first position!',
    add_position: 'Add Position',
    portfolio_management: 'Position management and PnL tracking',
    low_risk_portfolio: 'Low-risk portfolio from the team. View only.',
    portfolio_not_configured: 'RUKOS_CRYPTO portfolio is not yet configured by admin.',
    edit_position: 'Edit Position',
    fill_all_fields: 'Fill in all fields',
    position_updated: 'Position updated',
    position_added: 'Position added',
    position_deleted: 'Position deleted',
    delete_error: 'Delete error',
    error: 'Error',
    save: 'Save',
    add: 'Add',
    ticker_placeholder: 'Ticker (BTC, ETH, SOL...)',
    amount: 'Amount',
    entry_price: 'Entry Price ($)',
    note_optional: 'Note (optional)',
    total2_desc: 'All except BTC',
    total3_label: 'All except BTC/ETH',
    outperforming: 'outperforming',
    total_value_locked: 'Total Value Locked',
    total: 'Total',
    
    // Risk levels & statuses
    status_medium: 'MEDIUM',
    status_high: 'HIGH',
    status_low: 'LOW',
    status_extreme: 'EXTREME',
    status_critical: 'CRITICAL',
    status_elevated: 'ELEVATED',
    status_dangerous: 'DANGEROUS',
    status_normal: 'NORMAL',
    
    // Alert types
    alert_funding_spike: 'FUNDING SPIKE',
    alert_oi_divergence: 'OI DIVERGENCE',
    alert_whale_move: 'WHALE MOVE',
    alert_liquidation: 'LIQUIDATION',
    oi_spike: 'OI SPIKE',
    whale_move: 'WHALE MOVE',
    funding_spike: 'FUNDING SPIKE',
    liquidation: 'LIQUIDATION',
    
    // API messages translations
    msg_funding_overheated: 'Funding rate - market overheated',
    msg_oi_price_flat: 'OI up while price flat',
    msg_price_down_oi_up: 'Price down, OI up',
  }
};

// External links for data sources
export const dataSourceLinks = {
  coingecko: 'https://www.coingecko.com',
  coinmarketcap: 'https://coinmarketcap.com',
  coinglass: 'https://www.coinglass.com',
  arkham: 'https://platform.arkhamintelligence.com',
  sosovalue: 'https://sosovalue.xyz',
  glassnode: 'https://glassnode.com',
  alternative_me: 'https://alternative.me/crypto/fear-and-greed-index',
  deribit: 'https://www.deribit.com',
  hyperliquid: 'https://app.hyperliquid.xyz',
  defillama: 'https://defillama.com',
  tradingview: 'https://www.tradingview.com',
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ru' ? 'en' : 'ru');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export { translations };
